#document settings
title: Federal Spending Transparency 
desc: "Collaboration Space"
url: //fedspendingtransparency.github.io/
repo_name: fedspendingtransparency.github.io
branch: master

#global settings, no need to change these
root_url: //fedspendingtransparency.github.io
org_name: fedspendingtransparency

# default build settings for running locally, no need to edit
pymgemnts: true
exclude: ["script", "vendor", "Gemfile", "Gemfile.lock", "config.ru", "Procfile", "Rakefile", "readme.md"]
markdown: kramdown
relative_permalinks: false
